import SessionWrapper from '@/components/SessionWrapper';
import '../styles/globals.css';
import LayoutDefault from '@/components/layout/LayoutDefault.tsx/LayoutDefault';
import { MantineProvider, createTheme } from '@mantine/core';
import StoreProvider from '@/app/StoreProvider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const theme = createTheme({
  fontFamily: 'Open Sans, sans-serif',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <SessionWrapper>
        <html lang='en'>
          <body suppressHydrationWarning={false}>
            <div className='flex justify-center overflow-x-hidden'>
              <MantineProvider theme={theme}>
                <LayoutDefault>{children}</LayoutDefault>
              </MantineProvider>
            </div>
          </body>
        </html>
      </SessionWrapper>
    </StoreProvider>
  );
}
